import mongoose from "mongoose";
import dotenv from "dotenv";
import MenuCategory from "../models/MenuCategory.js";
import MenuItem from "../models/MenuItem.js";

dotenv.config();

const menuData = [
  {
    name: "Welcome Drink - Mocktail",
    slug: "mocktail",
    order: 1,
    items: [
      { name: "Pine Colada", description: "Pineapple Juice With Vanilla Icecream, Soda Sprite", price: 150, quantity: "250ml" },
      { name: "Fruit Punch", description: "Orange Juice Crash, Fanta Apple Soda", price: 140, quantity: "250ml" },
      { name: "Strawberry Colada", description: "Strawberry Crush With Icecream, Soda Sprite", price: 145, quantity: "250ml" },
      { name: "Thunderbolt", description: "Orange Juice, Strawberry Juice, Soda Sprite", price: 140, quantity: "250ml" },
      { name: "Lemon Mint Mojito", description: "Fresh Lime, Fresh Mint With Lime Juice Soda", price: 145, quantity: "250ml" },
      { name: "Kiwi Mint Cool", description: "Mojito Lime Mint Kiwi Ginger", price: 160, quantity: "250ml" },
      { name: "Blue Lagoon", description: "Sprite, Sugar Syrup", price: 145, quantity: "250ml" },
      { name: "Pineapple Juice", description: "Pineapple, Sugar Syrup", price: 145, quantity: "250ml" },
    ],
  },
  {
    name: "Salad",
    slug: "salad",
    order: 2,
    items: [
      { name: "Green Salad", price: 80, quantity: "250gm" },
      { name: "Mexican Salad", price: 159, quantity: "250gm" },
      { name: "Russian Salad", price: 159, quantity: "250gm" },
      { name: "Cucumber / Tamoto Salad", price: 80, quantity: "250gm" },
      { name: "Corn Potato Salad", price: 149, quantity: "250gm" },
      { name: "Apple Pasta Salad", price: 169, quantity: "250gm" },
      { name: "Peanut Salad", price: 149, quantity: "250gm" },
    ],
  },
  {
    name: "Khane ke Pehle",
    slug: "khane-ke-pehle",
    order: 3,
    items: [
      { name: "Veg Raita", description: "Vegetable", price: 100, quantity: "150gm" },
      { name: "Plain Raita", description: "Jeera Powder, Chat Masala, Macle, Bondi, Tomate, Onion", price: 130, quantity: "150gm" },
      { name: "Bondi Raita", price: 130, quantity: "150gm" },
      { name: "Mint Raita", price: 130, quantity: "150gm" },
      { name: "Chafed Mint", price: 130, quantity: "150gm" },
      { name: "Fruit Raita", price: 140, quantity: "150gm" },
      { name: "Pineapple Raita", price: 150, quantity: "150gm" },
    ],
  },
  {
    name: "Khane ke Sath Sath",
    slug: "khane-ke-sath-sath",
    order: 4,
    items: [
      { name: "Rosted Papad", price: 30, quantity: "" },
      { name: "Masala Papad", price: 45, quantity: "" },
      { name: "Rosted Papad Masala", price: 55, quantity: "" },
      { name: "Cheese Masala Papad", price: 70, quantity: "" },
      { name: "Sev Masala Papad", price: 50, quantity: "" },
      { name: "Fry Papad", price: 35, quantity: "" },
      { name: "Butter Milk", price: 40, quantity: "" },
      { name: "Pudina Butter Milk", price: 45, quantity: "" },
      { name: "SP Patiyala Butter Milk", price: 145, quantity: "" },
      { name: "Plain Curd", price: 70, quantity: "" },
      { name: "Masala Curd Rice", description: "Indian Masala With Rice", price: 130, quantity: "" },
    ],
  },
  {
    name: "Varity of Hot Soup",
    slug: "hot-soup",
    order: 5,
    items: [
      { name: "Asian Green Soup", description: "Authentic Boiled And Delicious Soup Cooked In Spinach", price: 169, quantity: "250ml" },
      { name: "Asian Red Garlic Fry Soup", description: "Coconut Milk, Fry Garlic, Vegetable", price: 149, quantity: "250ml" },
      { name: "Broccoli Almond Soup", description: "The Soup made of Broccoli Garnished and Almond", price: 199, quantity: "250ml" },
      { name: "Chatar Broccoli Almond Soup", description: "Cheese Milk Almond", price: 199, quantity: "250ml" },
      { name: "Khaw se Soup", description: "Fry Potato, Laccha Onion, Milk, Chop Veg, Mexican", price: 189, quantity: "250ml" },
      { name: "Roasted Bell Pepper Soup", description: "13 Bell Pepper, Tomato Base", price: 149, quantity: "250ml" },
      { name: "Hot 'N' Sour Soup", description: "A Dark Brown Chinese Soup With Ginger & Garlic", price: 150, quantity: "250ml" },
      { name: "Veg. Manchow Soup", description: "Fry Noodles, Julian Base, Ginger Garlic", price: 150, quantity: "250ml" },
      { name: "Cheese Corn Tomato Soup", description: "Corn Cheese Tomato Base", price: 150, quantity: "250ml" },
      { name: "Tomato Basil", description: "Tomato Base, Basil Chop", price: 130, quantity: "250ml" },
      { name: "Minestrone Soup", description: "Veg, Chop, Bag Beans, Cheese Vegetable", price: 130, quantity: "250ml" },
      { name: "Coconut Cream Soup", price: 180, quantity: "250ml" },
      { name: "Lemon Coriander Soup", description: "Lemon, Vegetable, Thickness", price: 150, quantity: "250ml" },
      { name: "Corn Mushroom Soup", description: "Mushroom, Corn", price: 149, quantity: "250ml" },
      { name: "Mushroom Soup", description: "Mushroom", price: 149, quantity: "250ml" },
      { name: "Mexican Tex Mex Soup", description: "Bell Pepper, Rajma Tortilla", price: 149, quantity: "250ml" },
      { name: "Mexican Tortilla Soup", description: "Tangy & Spicy beans based soup with Crispy Tortilla", price: 169, quantity: "250ml" },
      { name: "Mexican Chilly Beans Soup", description: "Chilly, Palak, Rajma, Base Beans", price: 139, quantity: "250ml" },
      { name: "Thai Tomion Soup", description: "English Vegetable, Coconut Milk, Thai Post", price: 180, quantity: "250ml" },
      { name: "Cauliflower Cheese Soup", description: "Cauliflower, Pest & Cheese", price: 149, quantity: "250ml" },
      { name: "Fresh Onion Soup", description: "Onion Fry, Clear, Cheese Bread Crush", price: 139, quantity: "250ml" },
      { name: "Mexican Soya Lodhan Soup", description: "Palak Base, Jeera Powder, Rajma Pesto & Chilly", price: 159, quantity: "250ml" },
      { name: "Palak Garlic Soup", price: 179, quantity: "250ml" },
    ],
  },
  {
    name: "Chinese Starter & Oriental",
    slug: "chinese-starter-oriental",
    order: 6,
    items: [
      { name: "Skechers Roll", description: "Cheesy, Vegetable, Jalapeno & Olives", price: 279, quantity: "350gm" },
      { name: "Panner Chilli / Dry / Gravy", description: "Danish Cutting, Bell Pepper, Onion", price: 285, quantity: "350gm" },
      { name: "Veg. Spring Roll", description: "Julian Veg. & Garlic Sauce", price: 245, quantity: "350gm" },
      { name: "Veg. Manchurian Dry", description: "Veg Chopping Carlin Ginger Onion", price: 220, quantity: "350gm" },
      { name: "Veg. Crispy", description: "Veg. Schezwan Sauce", price: 250, quantity: "350gm" },
      { name: "Baby Patato Crispy", description: "Honey Chilly Lifestyle Sauce", price: 245, quantity: "350gm" },
      { name: "Schezwan Karari Paneer Dry", description: "Paped Schezwan Sauce", price: 275, quantity: "350gm" },
      { name: "Chinese Paneer Cigar", description: "Schezwan Sauce", price: 259, quantity: "350gm" },
      { name: "Veg. Cigar", description: "Sprout Beans Vegetable", price: 249, quantity: "350gm" },
      { name: "Chinese Bhel", price: 269, quantity: "350gm" },
      { name: "Veg. Hakka Noodles", price: 200, quantity: "350gm" },
      { name: "Panner Cheese Roll", price: 285, quantity: "350gm" },
      { name: "Schezwan Potato Dry", description: "Schezwan Sauce", price: 199, quantity: "350gm" },
      { name: "Paneer Manchurian Dry", description: "Garlic Chop Chap Onion", price: 275, quantity: "350gm" },
      { name: "Schezwan Paneer Dry", description: "Schezwan Sauce", price: 259, quantity: "350gm" },
      { name: "Veg. 65", description: "Vegetable, Curd Curry Ral, Schezwan Sauce", price: 250, quantity: "350gm" },
      { name: "Baby Corn Golden Dry", description: "Honey Chilly Sauce", price: 259, quantity: "350gm" },
      { name: "Potato Chilly Dry", description: "Aloo Julian Crispy, Honey Chilly", price: 199, quantity: "350gm" },
      { name: "American Chopsuey", price: 235, quantity: "350gm" },
      { name: "Chinese Chopsuey", price: 235, quantity: "350gm" },
      { name: "Singapore Noodles", description: "Veg. & Pineapple", price: 220, quantity: "350gm" },
      { name: "Corn Ginger Fry Rice", description: "Corn, Ginger, Chilly", price: 219, quantity: "350gm" },
      { name: "Cottage Chez, Ginger Fry Rice", description: "Cottage Cheese Corn, Ginger, Chilly", price: 239, quantity: "350gm" },
      { name: "Veg. Fry Rice", description: "Vegitabel With Rice", price: 189, quantity: "350gm" },
      { name: "Irani Fry Rice", description: "Fry Noodles, Panner, English Veg.", price: 229, quantity: "350gm" },
      { name: "Corn Capsicum Fry Rice", description: "Corn 3 Type Capsicum", price: 229, quantity: "350gm" },
    ],
  },
  {
    name: "Tandoori Stater Ki Hatti",
    slug: "tandoori-starter",
    order: 7,
    items: [
      { name: "Tandoor Platter Dry", description: "Paneer Tikka: Hariyali Tikka, Reshmi Tikka, Mushroom", price: 399, quantity: "450gm" },
      { name: "Tandoor Mushroom Dry", description: "Staff Mushroom Masala", price: 269, quantity: "350gm" },
      { name: "Paneer Tikka Dry", description: "Soft Cottage Cheese Marinated in Indian Spices", price: 299, quantity: "350gm" },
      { name: "Pudina Paneer Tikka Dry", description: "Pudina Paste, Chopped Pudina, Indian Masala", price: 269, quantity: "350gm" },
      { name: "Gobi Tandoor Dry", description: "Yellow Curd Paste & Indian Masala", price: 259, quantity: "350gm" },
      { name: "Afghani Paneer Tikka Dry", description: "Creamy, Curd, Cheese, Indian Masala", price: 269, quantity: "350gm" },
      { name: "Paneer Kali Mirch", description: "Black Pepper, Chilly Paste, Indian Masala", price: 269, quantity: "350gm" },
      { name: "Paneer Lasooni Tikka Dry", description: "Garlic, Cream & Curd", price: 259, quantity: "350gm" },
      { name: "Karari Corn Tikki", description: "Corn, Aloo & Panko Crumbe", price: 249, quantity: "350gm" },
      { name: "Hara - Bhara Kabab", description: "Vegetable, Palak, Green Chilli", price: 249, quantity: "350gm" },
      { name: "Vegetable Seekh Kabab", description: "Vegetable, Fine Chopped, Indian Masala", price: 259, quantity: "350gm" },
      { name: "Paneer Seekh Kabab", description: "Paneer, Mawa, Curd & Vegetable", price: 279, quantity: "350gm" },
      { name: "Tandoor Broccoli Dry", description: "Green Paste, Indian Masala & Curd, Broccoli", price: 279, quantity: "350gm" },
      { name: "Papad da Kawab", price: 245, quantity: "350gm" },
      { name: "Soya Chap", price: 230, quantity: "350gm" },
    ],
  },
  {
    name: "Mexican Food",
    slug: "mexican-food",
    order: 8,
    items: [
      { name: "Mexican Rice", description: "English Veg. & Curry", price: 259, quantity: "350gm" },
      { name: "Mexican Titbit Rice", description: "Green Curry & Vegetable", price: 254, quantity: "350gm" },
      { name: "Mexican Hot Pot Rice", description: "Cheese Nachos Veg. Curry", price: 289, quantity: "350gm" },
      { name: "Mexican Platter", description: "Mexican Balls and Curry Cheese Ball", price: 399, quantity: "350gm" },
      { name: "Mexican Tortilla Rice", description: "Solsa Curry", price: 269, quantity: "350gm" },
      { name: "Mexican Corn Roll", description: "Cheese, Jalapeno & Paneer", price: 279, quantity: "350gm" },
      { name: "Mexican Corn Pops", description: "Corn, Cheese, Jalapeno Topping", price: 269, quantity: "350gm" },
      { name: "Mexican Cute Roll", description: "Cheese, Jalapeno Topping", price: 269, quantity: "350gm" },
      { name: "Mexican Nachos", description: "Cheese Sauce, Bell Pepper Chep", price: 269, quantity: "350gm" },
      { name: "Mexican Kasa Dila", description: "Cheese, Paneer, Rajma, English Veg.", price: 284, quantity: "350gm" },
      { name: "Mexican Barbecue", description: "Bell Pepper, Paneer, Neapolitan Sauce", price: 299, quantity: "350gm" },
      { name: "Mexican Tacos", description: "Cheese, Rajma, Bell Pepper", price: 299, quantity: "350gm" },
      { name: "Noci Pasta", description: "Alfredo Sauce, Bell Pepper & Neapolitan Sauce", price: 279, quantity: "320gm" },
      { name: "Penne Pasta", description: "Neapolitan Sauce, Cheese", price: 259, quantity: "320gm" },
      { name: "Pasta Mista", description: "Vegetable, Mix Pasta & Red Sauce", price: 269, quantity: "320gm" },
      { name: "Farfalle Pasta", description: "Taste Sauce, Cheese", price: 269, quantity: "320gm" },
      { name: "Schezwan Fusilli Pasta", description: "Schezwan Sauce & Cheese", price: 269, quantity: "320gm" },
      { name: "Mexican Corn Roll (3 Beans)", description: "3 types of Beans, Neapolitan Sauce", price: 279, quantity: "350gm" },
    ],
  },
  {
    name: "Thai Food",
    slug: "thai-food",
    order: 9,
    items: [
      { name: "Lemon Green Garlic Sauce", description: "Fried Noodles, Peanut", price: 279, quantity: "400gm" },
      { name: "Thai Peanut Noodles", description: "Peanut, Thai Noodles & English Veg.", price: 279, quantity: "400gm" },
      { name: "Green Thai Curry", description: "Coconut Milk, English Vegetable", price: 289, quantity: "400gm" },
      { name: "Red Thai Curry", description: "Coconut Milk, English Vegetable", price: 289, quantity: "400gm" },
      { name: "London Thai Curry Yellow", description: "Coconut Milk, English Vegetable", price: 289, quantity: "400gm" },
      { name: "Thai Flat Noodles", description: "Green Garlic, Peanut & Cheese", price: 299, quantity: "400gm" },
      { name: "Barsetto Green Rice", description: "Chopped Onions, Garlic paste, Spinach", price: 269, quantity: "400gm" },
      { name: "Barsetto Red Rice", description: "Chopped Onions, Garlic paste, Spinach", price: 259, quantity: "400gm" },
      { name: "Barsetto Rice Alfredo", description: "Coconut Oil, Green Chili, Tej Patta", price: 259, quantity: "400gm" },
    ],
  },
  {
    name: "Varity of Paneer",
    slug: "paneer-varieties",
    order: 10,
    items: [
      { name: "Bawarchi Special Paneer", price: 299, quantity: "350gm" },
      { name: "Paneer Tikka Masala", price: 249, quantity: "350gm" },
      { name: "Paneer Amritsari", price: 259, quantity: "350gm" },
      { name: "Paneer Rill Mill", price: 259, quantity: "350gm" },
      { name: "Paneer Tawa Masala", price: 249, quantity: "350gm" },
      { name: "Paneer Hyderabadi", price: 255, quantity: "350gm" },
      { name: "Paneer Balti / Kadai", price: 249, quantity: "350gm" },
      { name: "Paneer Handi", price: 249, quantity: "350gm" },
      { name: "Burhani Dum Paneer", price: 279, quantity: "350gm" },
      { name: "Paneer Diwani Handi", price: 260, quantity: "350gm" },
      { name: "Paneer Pasanda", price: 280, quantity: "350gm" },
      { name: "Paneer Mutter Masala", price: 190, quantity: "350gm" },
      { name: "Paneer Angara", price: 299, quantity: "350gm" },
      { name: "Paneer Bhurji", price: 269, quantity: "350gm" },
      { name: "Bawarchi Ghotala", price: 279, quantity: "350gm" },
      { name: "Paneer Lavabdar", price: 279, quantity: "350gm" },
      { name: "Palak Paneer", price: 230, quantity: "350gm" },
      { name: "Cheese Butter Masala", price: 259, quantity: "350gm" },
      { name: "Paneer Butter Masala", price: 245, quantity: "350gm" },
      { name: "Paneer Kali Mirch Masala", price: 249, quantity: "350gm" },
      { name: "Paneer Afgani", price: 255, quantity: "350gm" },
      { name: "Paneer Lasniyaa", price: 255, quantity: "350gm" },
      { name: "Paneer Toofani", price: 245, quantity: "350gm" },
      { name: "Paneer Maharani", price: 255, quantity: "350gm" },
    ],
  },
  {
    name: "Roti Tawa & Tandoori",
    slug: "roti-tawa-tandoori",
    order: 11,
    items: [
      { name: "Tandoori Plain Roti", price: 25, quantity: "22gm" },
      { name: "Tandoori Butter Roti", price: 30, quantity: "24gm" },
      { name: "Missi Roti", price: 80, quantity: "60gm" },
      { name: "Tawa Butter Roti", price: 20, quantity: "18gm" },
      { name: "Plain Tawa Roti", price: 18, quantity: "16gm" },
      { name: "Butter Naan", price: 55, quantity: "45gm" },
      { name: "Cheese Naan", price: 99, quantity: "80gm" },
      { name: "Cheese Garlic Naan", price: 130, quantity: "100gm" },
      { name: "Garlic Naan", price: 130, quantity: "110gm" },
      { name: "Stuff Kulcha", price: 80, quantity: "80gm" },
      { name: "Butter Kulcha", price: 60, quantity: "100gm" },
      { name: "Lachha Paratha", price: 80, quantity: "50gm" },
      { name: "Tawa Butter Paratha", price: 75, quantity: "80gm" },
      { name: "Rumali Roti", price: 120, quantity: "110gm" },
    ],
  },
  {
    name: "Dal & Khichdi Junction",
    slug: "dal-khichdi",
    order: 12,
    items: [
      { name: "Dal Makhani", description: "3 Type Dal & Red Gravy", price: 190, quantity: "300gm" },
      { name: "Dal Fry", description: "Own Type Dal", price: 165, quantity: "300gm" },
      { name: "Dal Tadka", description: "Soft Cottage Cheese Marinated in Indian Spices", price: 175, quantity: "300gm" },
      { name: "Dal Palak", description: "Yellow Curd Paste & Indian Masala", price: 170, quantity: "300gm" },
      { name: "Plain Dal", description: "Creamy, Curd, Cheese, Indian Masala", price: 130, quantity: "300gm" },
      { name: "Dal Pachrangi", description: "Black Pepper, Chilly Paste, Indian Masala", price: 190, quantity: "300gm" },
      { name: "Dal Butter", description: "Garlic, Cream & Curd", price: 180, quantity: "300gm" },
      { name: "Garlic Fry", description: "Garlic", price: 145, quantity: "300gm" },
      { name: "Veg. Khichdi / Kadhi", description: "3 Type Dal & Red Gravy", price: 200, quantity: "300gm" },
      { name: "Masala Khichdi", description: "Own Type Dal", price: 170, quantity: "300gm" },
      { name: "Moon Dal Khichdi", description: "Soft Cottage Cheese Marinated in Indian Spices", price: 180, quantity: "300gm" },
      { name: "Butter Khichdi", description: "Pudina Paste, Chopped Pudina, Indian Masala", price: 180, quantity: "300gm" },
      { name: "Palak Khichdi", description: "Yellow Curd Paste & Indian Masala", price: 180, quantity: "300gm" },
      { name: "Masoor Dal Khichdi", description: "Creamy, Curd, Cheese, Indian Masala", price: 170, quantity: "300gm" },
      { name: "Garlic Fry Khichdi", description: "Black Pepper, Chilly Paste, Indian Masala", price: 170, quantity: "300gm" },
      { name: "Pasto Khichdi", description: "Garlic, Cream & Curd", price: 180, quantity: "300gm" },
      { name: "Punjabi Kadhi", price: 145, quantity: "300gm" },
    ],
  },
  {
    name: "Basmati Khazana",
    slug: "basmati-khazana",
    order: 13,
    items: [
      { name: "Veg. Hyderabadi Biryani", description: "Base Palak", price: 199, quantity: "350gm" },
      { name: "Veg. Dam Biryani", description: "Vegetable", price: 210, quantity: "350gm" },
      { name: "Aloo Dum Biryani", description: "Curd Patato", price: 200, quantity: "350gm" },
      { name: "Lakhnavi Biryani", description: "Vegetable, Cheese & Red Gravy", price: 209, quantity: "350gm" },
      { name: "Veg. Pulao / Tawa Pulao", description: "All Vegetable", price: 155, quantity: "350gm" },
      { name: "Peas Pulao", description: "Green Peas", price: 209, quantity: "350gm" },
      { name: "Jeera Rice", description: "Jeera Butter", price: 150, quantity: "350gm" },
      { name: "Plain Rice / Steam Rice", description: "Boil Rice", price: 135, quantity: "350gm" },
      { name: "Laziz Biryani", description: "Vegetable, Fry Onion & Cheese", price: 200, quantity: "350gm" },
      { name: "Indian Fry Rice", price: 215, quantity: "350gm" },
      { name: "Handi Pulao", price: 189, quantity: "350gm" },
      { name: "English Vegetable Rice", price: 199, quantity: "350gm" },
    ],
  },
  {
    name: "Bread Station With Pizza & French Fries",
    slug: "bread-pizza-fries",
    order: 14,
    items: [
      { name: "Veg. Sandwich", description: "Vegetable", price: 80, quantity: "200gm" },
      { name: "Cheese Sandwich", description: "Cheese", price: 100, quantity: "200gm" },
      { name: "Veg. Club Sandwich", description: "Cucumber, Vegetable Cheese", price: 150, quantity: "220gm" },
      { name: "Bread Butter", description: "Butter", price: 50, quantity: "150gm" },
      { name: "Mix Fruit Jam Sandwich", description: "Fruit Jam", price: 70, quantity: "170ml" },
      { name: "Italian Pizza", description: "Neapolitan Sauce & Vegetables", price: 176, quantity: "9.5/19cm" },
      { name: "Margherita Pizza", description: "Tomato Slice and Cheese", price: 175, quantity: "9.5/19cm" },
      { name: "Khari Pizza", description: "Vegetable, Thousand Sauce & Cheese", price: 180, quantity: "9.5/19cm" },
      { name: "Double Cheese Pizza", description: "Cheese, Neapolitan Sauce", price: 199, quantity: "9.5/19cm" },
      { name: "Cheese Pizza", description: "Cheese, Neapolitan Sauce", price: 160, quantity: "9.5/19cm" },
      { name: "Mexican Pizza", description: "Rajma, Corn, Cheese, Neapolitan Sauce", price: 199, quantity: "9.5/19cm" },
      { name: "Aloo Veggie. Fry", description: "Aloo Veg", price: 150, quantity: "250ml" },
      { name: "French Fries", description: "Aloo Finger", price: 120, quantity: "120ml" },
      { name: "French Fries Cheese", description: "Aloo Finger & Cheese", price: 140, quantity: "120ml" },
      { name: "Green Masala Cheese Toast", description: "Cheese & Tomato Topping", price: 220, quantity: "200gm" },
      { name: "Cheese Chilly Toast", price: 180, quantity: "250ml" },
    ],
  },
  {
    name: "Tadkta Fadkta Sizzler & Baked Dish",
    slug: "sizzlers-baked",
    order: 15,
    items: [
      { name: "Bawarchi Special Sizzler", description: "Penne Pasta, Korean Rice Balls, Neapolitan Sauce", price: 499, quantity: "500gm" },
      { name: "Shashlik Sizzlers", description: "Rice, Paneer, Yellow Sauce", price: 439, quantity: "500gm" },
      { name: "Mexican Sizzlers", description: "Mexican Rice, Corn Chaat & Mix Veg.", price: 440, quantity: "500gm" },
      { name: "Chinese Sizzlers", description: "Rice, Noddles & Manchurian", price: 380, quantity: "500gm" },
      { name: "Italian Sizzlers", description: "Penne Pasta, Capsicum Tomato & Veg.", price: 439, quantity: "500gm" },
      { name: "Thai Sizzlers", description: "Thai Lemon Green Garlic Sauce, Thai Noodles", price: 429, quantity: "500gm" },
      { name: "Tandoori Sizzlers", description: "3 Types Paneer, Broccoli Mushroom", price: 419, quantity: "500gm" },
      { name: "B.B.Q. Sizzlers", description: "Paneer, B.B.Q. Sauce, Chop Capsicum Tomato", price: 429, quantity: "500gm" },
      { name: "Continental Sizzlers", description: "Vegetable, Paneer Pasta, Brown Sauce", price: 419, quantity: "500gm" },
      { name: "Arabic Sizzlers", description: "Noodles, Rice, Veg. & Noki Pasta", price: 429, quantity: "500gm" },
      { name: "Veg. Lazaniya", description: "Vegetables, Neapolitan Sauce, Cheese", price: 299, quantity: "325gm" },
      { name: "Baked Macaroni Apple", description: "Cheese, Macaroni & Apple", price: 300, quantity: "325gm" },
      { name: "Baked Macaroni With Dry Fruit", description: "Cheese, Macaroni & Fruit Coctel", price: 330, quantity: "325gm" },
      { name: "Baked Macaroni With P.A", description: "Pineapple, Alfredo Sauce", price: 280, quantity: "325gm" },
      { name: "Baked Spaghetti With P.A", description: "Boiled Macaroni, Chopped Pineapple, Salt & Pepper", price: 270, quantity: "325gm" },
    ],
  },
  {
    name: "Milk Shake & Lassi Pyala",
    slug: "milkshake-lassi",
    order: 16,
    items: [
      { name: "Vanilla Shake/Strawberry", description: "Vanilla Extract, Strawberries, Milk", price: 140, quantity: "250ml" },
      { name: "Chocolate Shake", description: "Milk, Vanilla or Chocolate, and Chocolate Syrup", price: 150, quantity: "250ml" },
      { name: "Kesar Pista / Rajbhog Shake", description: "Milk, Kesar & Pista", price: 160, quantity: "250ml" },
      { name: "Cold Coffee", description: "Milk, Coffee with Cold", price: 130, quantity: "250ml" },
      { name: "Cold Coffee with Ice Cream", description: "Milk, Coffee with Vanilla Ice Cream", price: 160, quantity: "250ml" },
      { name: "Oreo Cookie Shake", description: "Vanilla Ice Cream, Milk, & Oreo Cookie", price: 149, quantity: "250ml" },
      { name: "Hot Milk", description: "Milk, Sweeteners like Sugar or Honey", price: 99, quantity: "250ml" },
      { name: "Bournvita", description: "Wheat, Sugar, Cocoa Solids, Milk Solids", price: 129, quantity: "250ml" },
      { name: "Lassi (Sweet / Salted)", description: "Sugar & Curd", price: 99, quantity: "250ml" },
      { name: "Sp. Dry Fruit Lassi", description: "Loaded Curd Mava And Dry Fruits With Flavour Of Your Choice Kesar/Rose/Khus With Ice Cream", price: 129, quantity: "250ml" },
      { name: "Rajbhog Lassi", description: "Curd, Sugar, Rajbhog Flavoured", price: 149, quantity: "250ml" },
      { name: "Ice Cream With Lassi", description: "Milk, Vanilla", price: 120, quantity: "250ml" },
      { name: "Orange Lassi", description: "Orange Syrup, Curd, Sugar", price: 120, quantity: "250ml" },
      { name: "Mango Lassi", description: "Mangoes Pulp, Plain Yogurt, and Milk", price: 129, quantity: "250ml" },
    ],
  },
  {
    name: "Vidai Se Pehle (Desserts)",
    slug: "desserts",
    order: 17,
    items: [
      { name: "Jafrani Kheer", description: "Kesar, Milk & Dry Fruit", price: 169, quantity: "250ml" },
      { name: "Mund Dal Ka Halva", description: "Dry Fruit, Mawa & Milk", price: 150, quantity: "250ml" },
      { name: "Gulab Jamun", description: "Milk, Sugar Syrup", price: 90, quantity: "4pic" },
      { name: "Sundae Truffle Ice Cream", description: "Apple, Tutti Frutti, Chocolate Sauce", price: 209, quantity: "200ml" },
      { name: "Chocolate Ice Cream", description: "Chocolate Sauce", price: 70, quantity: "100ml" },
      { name: "Kaju Draksh", description: "Dry Fruits", price: 70, quantity: "100ml" },
      { name: "American 'N' Nuts", description: "Dry Fruits", price: 100, quantity: "150ml" },
      { name: "Sizzling Brownie", description: "Brownie, Kaju Hot", price: 199, quantity: "200gm" },
      { name: "Strawberry Rose Dessert Cold", description: "Rice, Strawberry Syrup, Dry Fruit", price: 199, quantity: "200gm" },
      { name: "Mango Ice Cream", description: "Mango Crush", price: 99, quantity: "200gm" },
      { name: "Butter Scotch Ice Cream", price: 70, quantity: "100ml" },
      { name: "Vanilla / Strawberry Ice Cream", price: 50, quantity: "100ml" },
    ],
  },
];

const seedMenu = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected for seeding...");

    await MenuCategory.deleteMany();
    await MenuItem.deleteMany();

    for (const cat of menuData) {
      const category = await MenuCategory.create({
        name: cat.name,
        slug: cat.slug,
        order: cat.order,
      });

      const itemsWithCategory = cat.items.map((item) => ({
        ...item,
        category: category._id,
      }));

      await MenuItem.insertMany(itemsWithCategory);
      console.log(`Seeded category: ${cat.name} (${cat.items.length} items)`);
    }

    console.log("Menu seeding complete!");
    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
};

seedMenu();